### ISSUE TITLE
Error while trying to train on AlgoLisp

### ISSUE THREAD

**Issue by Sumith1896** [nearai/program_synthesis#11]
Hi all, thanks for making this open-source! I was tinkering with this and wanted to train the model as per README on AlgoLisp but was running into this:
```
$ python train.py --model_type=seq2seq --model_dir=models/seq2seq
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from program_synthesis.algolisp import models
  File "/home/sumith/software/anaconda3/lib/python3.6/site-packages/program_synthesis/algolisp/models/__init__.py", line 2, in <module>
    from program_synthesis.algolisp.models import seq2seq_model
  File "/home/sumith/software/anaconda3/lib/python3.6/site-packages/program_synthesis/algolisp/models/seq2seq_model.py", line 24, in <module>
    from program_synthesis.algolisp.models.base import InferenceResult, MaskedMemory, get_attn_mask
  File "/home/sumith/software/anaconda3/lib/python3.6/site-packages/program_synthesis/algolisp/models/base.py", line 19, in <module>
    from program_synthesis.algolisp.tools import bleu
  File "/home/sumith/software/anaconda3/lib/python3.6/site-packages/program_synthesis/algolisp/tools/__init__.py", line 1, in <module>
    from program_synthesis.algolisp.tools.reporter import Reporter
ModuleNotFoundError: No module named 'program_synthesis.algolisp.tools.reporter'
```

**Comment by Sumith1896** [comment]
Installing in editable mode works, pip package is broken for algolistp (or not released?)

**Comment by ilblackdragon** [comment]
Removed for now install from PyPi - we are not really maintaining this package actively (switched to working on http://nearprotocol.com)
